stages:
    - build
    - release

build-master:
  image: pablomk7/luma3dsplgldr:latest
  stage: build
  services:
  only:
    - master
    - merge_requests
  before_script:
  script:
    - make
  artifacts:
    paths:
      - boot.firm
    expire_in: 1 week

release:
    image: inetprocess/gitlab-release
    stage: release
    only:
        - master
    script:
        - gitlab-release --message "luma3ds hourly $CI_COMMIT_SHORT_SHA" boot.firm
